# Problem regresji

Dodanie potrzenych bibliotek:

In [1]:
import tensorflow as tf 
from tensorflow import keras
import pandas as pd

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input

In [3]:
import numpy as np
import matplotlib.pyplot as plt

Podzielenie zaimportowanych danych na zbiór testowy i uczący się. W kazdym zbiorze znajdują się feature oraz label

In [4]:
(train_features, train_labels), (test_features, test_labels) = keras.datasets.boston_housing.load_data()


Wyświetlenie zbioru danych:

In [5]:
train_features

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

Nasz zbiór uczący sie naley nastepnie podzilic na zbiór treningowy i walidacyjny. Proporcje podziału
dobrałam na zasadzie 85-15 ale nie jest to sztywna zasada

In [6]:
train_features_full = train_features[:int(0.85*train_features.shape[0])]
valid_features_full = train_features[int(0.85*train_features.shape[0]):]
train_labels_full = train_labels[:int(0.85*train_features.shape[0]):]
valid_labels_full = train_labels[int(0.85*train_features.shape[0]):]

Kiedy mamy podzielone dane możemy w końcu przejść do napisania sieci neuronowej.
Używamy do tego celu biblioteki Keras z 
tensorflow. Sieć neuronową zaczynamy pisać poprzez odwołanie się do 
funkcji biblioteki Keraz. W argumentach podajemy warstwy sieci. Nastepnie kompilujemy model.

In [7]:
model = keras.Sequential([
        Dense(20, activation=tf.nn.relu, input_shape=[len(train_features[0])]),
        Dense(1)
    ])

model.compile(optimizer='adam', 
              loss='mse',
              metrics=['mae', 'mse'])

Metal device set to: Apple M1


2022-06-15 23:06:26.732013: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-15 23:06:26.732356: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Funkcja callbacks.ModelCheckpoint zapisuje najlepsze dopasowanie do pliku o nazwie model_regression.h5 Funkcja .fit
trenuje model na zbiorze treningowym oraz waliduje na zbiorze walidacyjnym.

In [8]:
checkpoint = keras.callbacks.ModelCheckpoint("model_regression.h5", save_best_only=True)
model.fit(x = train_features_full, y = train_labels_full, validation_data=(valid_features_full, valid_labels_full), epochs=256, verbose=1, callbacks= checkpoint)

2022-06-15 23:06:26.922837: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


Epoch 1/256


2022-06-15 23:06:27.248376: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


11/11 [==============================] - 1s 29ms/step - loss: 17603.8008 - mae: 128.0533 - mse: 17603.8008 - val_loss: 15212.4980 - val_mae: 119.0441 - val_mse: 15212.4980
Epoch 2/256
11/11 [==============================] - 0s 9ms/step - loss: 11885.7500 - mae: 104.1655 - mse: 11885.7500 - val_loss: 10246.0645 - val_mae: 96.9306 - val_mse: 10246.0645
Epoch 3/256
 1/11 [=>............................] - ETA: 0s - loss: 9404.2891 - mae: 92.3828 - mse: 9404.2891

2022-06-15 23:06:28.230286: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


11/11 [==============================] - 0s 10ms/step - loss: 7705.8208 - mae: 83.7256 - mse: 7705.8208 - val_loss: 6606.7300 - val_mae: 77.9801 - val_mse: 6606.7300
Epoch 4/256
11/11 [==============================] - 0s 10ms/step - loss: 4848.9033 - mae: 65.7519 - mse: 4848.9033 - val_loss: 4096.0103 - val_mae: 60.6555 - val_mse: 4096.0103
Epoch 5/256
11/11 [==============================] - 0s 10ms/step - loss: 2992.8472 - mae: 50.4760 - mse: 2992.8472 - val_loss: 2574.0139 - val_mae: 46.9384 - val_mse: 2574.0139
Epoch 6/256
11/11 [==============================] - 0s 11ms/step - loss: 1962.4979 - mae: 39.3908 - mse: 1962.4979 - val_loss: 1690.8228 - val_mae: 37.4334 - val_mse: 1690.8228
Epoch 7/256
11/11 [==============================] - 0s 10ms/step - loss: 1407.3585 - mae: 32.5616 - mse: 1407.3585 - val_loss: 1225.8748 - val_mae: 30.6142 - val_mse: 1225.8748
Epoch 8/256
11/11 [==============================] - 0s 10ms/step - loss: 1093.1041 - mae: 27.3953 - mse: 1093.1041 - val_

Epoch 51/256
11/11 [==============================] - 0s 9ms/step - loss: 74.2335 - mae: 6.4712 - mse: 74.2335 - val_loss: 87.4686 - val_mae: 6.1596 - val_mse: 87.4686
Epoch 52/256
11/11 [==============================] - 0s 7ms/step - loss: 73.3985 - mae: 6.4302 - mse: 73.3985 - val_loss: 88.7003 - val_mae: 6.0393 - val_mse: 88.7003
Epoch 53/256
11/11 [==============================] - 0s 9ms/step - loss: 72.9810 - mae: 6.3406 - mse: 72.9810 - val_loss: 87.3262 - val_mae: 6.0305 - val_mse: 87.3262
Epoch 54/256
11/11 [==============================] - 0s 8ms/step - loss: 72.3546 - mae: 6.2902 - mse: 72.3546 - val_loss: 88.0710 - val_mae: 5.9552 - val_mse: 88.0710
Epoch 55/256
11/11 [==============================] - 0s 9ms/step - loss: 71.9714 - mae: 6.3264 - mse: 71.9714 - val_loss: 84.9574 - val_mae: 6.0135 - val_mse: 84.9574
Epoch 56/256
11/11 [==============================] - 0s 8ms/step - loss: 71.3168 - mae: 6.2986 - mse: 71.3168 - val_loss: 86.0142 - val_mae: 5.9086 - val_mse: 

Epoch 100/256
11/11 [==============================] - 0s 9ms/step - loss: 56.9682 - mae: 5.4761 - mse: 56.9682 - val_loss: 68.5321 - val_mae: 5.2941 - val_mse: 68.5321
Epoch 101/256
11/11 [==============================] - 0s 8ms/step - loss: 57.1638 - mae: 5.3968 - mse: 57.1638 - val_loss: 69.0082 - val_mae: 5.2623 - val_mse: 69.0082
Epoch 102/256
11/11 [==============================] - 0s 9ms/step - loss: 56.3870 - mae: 5.4223 - mse: 56.3870 - val_loss: 68.0190 - val_mae: 5.2846 - val_mse: 68.0190
Epoch 103/256
11/11 [==============================] - 0s 7ms/step - loss: 56.2239 - mae: 5.4064 - mse: 56.2239 - val_loss: 68.7427 - val_mae: 5.2502 - val_mse: 68.7427
Epoch 104/256
11/11 [==============================] - 0s 9ms/step - loss: 55.9619 - mae: 5.4203 - mse: 55.9619 - val_loss: 67.4641 - val_mae: 5.2740 - val_mse: 67.4641
Epoch 105/256
11/11 [==============================] - 0s 8ms/step - loss: 56.2615 - mae: 5.3284 - mse: 56.2615 - val_loss: 68.5991 - val_mae: 5.2405 - val

11/11 [==============================] - 0s 8ms/step - loss: 42.4041 - mae: 4.6095 - mse: 42.4041 - val_loss: 51.8185 - val_mae: 4.9296 - val_mse: 51.8185
Epoch 197/256
11/11 [==============================] - 0s 8ms/step - loss: 42.0987 - mae: 4.6749 - mse: 42.0987 - val_loss: 49.8741 - val_mae: 4.9030 - val_mse: 49.8741
Epoch 198/256
11/11 [==============================] - 0s 8ms/step - loss: 42.2526 - mae: 4.7539 - mse: 42.2526 - val_loss: 52.3267 - val_mae: 4.9372 - val_mse: 52.3267
Epoch 199/256
11/11 [==============================] - 0s 8ms/step - loss: 42.4876 - mae: 4.5819 - mse: 42.4876 - val_loss: 49.7326 - val_mae: 4.9236 - val_mse: 49.7326
Epoch 200/256
11/11 [==============================] - 0s 8ms/step - loss: 42.0772 - mae: 4.7473 - mse: 42.0772 - val_loss: 50.1605 - val_mae: 4.9336 - val_mse: 50.1605
Epoch 201/256
11/11 [==============================] - 0s 8ms/step - loss: 42.0207 - mae: 4.6331 - mse: 42.0207 - val_loss: 51.0196 - val_mae: 4.9139 - val_mse: 51.0196


Podczas trenowania po zakończeniu każdej z epok wyświetlane są statystyki dotyczące funkcji loss 
gdzie los dotyczy zbioru treningowego a val_los zbioru walidacyjnego. Gdzie mae (Mean absolute error) a 
mse (Mean Squared Error)

Wyświetlamy wyniki dla pierwszych 5 wartości:

In [9]:
print(test_labels[:5])

[ 7.2 18.8 19.  27.  22.2]


In [10]:
predictions = model.predict(test_features)
print(predictions[:5].T)

[[ 7.204886 21.774988 23.163446 26.868504 24.375319]]


2022-06-15 23:06:52.736537: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Jak widać wyniki są zadowalające.
Następnie zapisujemy dane z 0 próbki do pliku csv aby potem przetestować na nich działanie sieci w matlabie.

In [11]:
test_features[0]

array([ 18.0846,   0.    ,  18.1   ,   0.    ,   0.679 ,   6.434 ,
       100.    ,   1.8347,  24.    , 666.    ,  20.2   ,  27.25  ,
        29.05  ])

In [15]:
np.savetxt('test.csv', test_features[0], delimiter=",")